name: "EMA APP"
iconUrl: "https://static.dotcms.com/assets/icons/apps/ema-icon.png"
allowExtraParameters: false 
description: "EMA APP"
params:
  proxyEditModeURL:
    value: ""
    hidden: false
    type: "STRING"
    label: "Proxy Edit Mode URL"
    hint: "Your rendering server and endpoint that dotCMS will be proxying the request to, including the port, e.g. https://myspa.com:3000"
    required: true
